/*********************************************************************
**
** Copyright (C) 2002-2014 Integrated Computer Solutions, Inc.
** All rights reserved.
**
** This file is part of the QicsTable software.
**
** See the top level README file for license terms under which this
** software can be used, distributed, or modified.
**
**********************************************************************/

/* XPM */
static const char *qicstable_logo_xpm[] = {
/* columns rows colors chars-per-pixel */
"102 82 175 2",
"   c #4C4C4C",
".  c #97CF16",
"X  c #99CF17",
"o  c #97CE19",
"O  c #9ACE1A",
"+  c #98D017",
"@  c #9AD018",
"#  c #9BCC23",
"$  c #9CC72F",
"%  c #9CCA2A",
"&  c #9DC735",
"*  c #9CC933",
"=  c #9DC63B",
"-  c #9DC839",
";  c #A3D32C",
":  c #A1CE36",
">  c #A0C63D",
",  c #A2CC3C",
"<  c #A6D23C",
"1  c #ACD93E",
"2  c #AEE238",
"3  c #B1E13B",
"4  c #9FBF50",
"5  c #A1BF56",
"6  c #A1BE5A",
"7  c #A2BC62",
"8  c #A3BA6A",
"9  c #A8BF6F",
"0  c #A3B770",
"q  c #A3B970",
"w  c #9EC442",
"e  c #9FC24D",
"r  c #9FC150",
"t  c #A0C345",
"y  c #A4CB44",
"u  c #A9CF44",
"i  c #A0C14E",
"p  c #A5CB4A",
"a  c #A9CE4C",
"s  c #A7D044",
"d  c #AAD442",
"f  c #ACD845",
"g  c #ADD64B",
"h  c #B1DF41",
"j  c #B2DC4C",
"k  c #A0C151",
"l  c #A9CB54",
"z  c #A4C45A",
"x  c #A9CB5B",
"c  c #AED453",
"v  c #B0D554",
"b  c #B3DB54",
"n  c #B4D75E",
"m  c #B4D95D",
"M  c #B9DD5D",
"N  c #B7E056",
"B  c #BCE855",
"V  c #BDE65C",
"C  c #ADCD63",
"Z  c #ACC768",
"A  c #B0CF67",
"S  c #B2CE6A",
"D  c #AFD161",
"F  c #B4D663",
"G  c #B7DD63",
"H  c #B9DD62",
"J  c #B6D46D",
"K  c #B8D26D",
"L  c #BADA6D",
"P  c #B2CD70",
"I  c #B7CE7E",
"U  c #B8CF7D",
"Y  c #B6D272",
"T  c #B9D274",
"R  c #B7D179",
"E  c #BAD37B",
"W  c #BAD878",
"Q  c #BEE465",
"!  c #BFE26A",
"~  c #C2EB5F",
"^  c #C6F25C",
"/  c #C8F35D",
"(  c #CDFA5F",
")  c #C1DD77",
"_  c #C1DE7A",
"`  c #C4EA63",
"'  c #C3E56F",
"]  c #C7EF6C",
"[  c #C9EE6E",
"{  c #C7F063",
"}  c #CDF66A",
"|  c #D2FD6D",
" . c #C2E374",
".. c #C7EC72",
"X. c #C9EC74",
"o. c #C6E57B",
"O. c #CAEB7B",
"+. c #CFF376",
"@. c #CFF27B",
"#. c #D7FF75",
"$. c #D3F37D",
"%. c #D5F97D",
"&. c #DBFF7A",
"*. c #B8CE84",
"=. c #C3DC82",
"-. c #C3DC88",
";. c #C8DF8D",
":. c #C8DC9B",
">. c #C7E284",
",. c #CCE786",
"<. c #CAE982",
"1. c #C7E189",
"2. c #CCE68B",
"3. c #CDE88B",
"4. c #D2ED8B",
"5. c #D4F584",
"6. c #D7FD83",
"7. c #DDFF83",
"8. c #D6F48C",
"9. c #D8F48E",
"0. c #DDFD8B",
"q. c #CDE494",
"w. c #CDE399",
"e. c #D3EC92",
"r. c #D3E79F",
"t. c #D3EA9C",
"y. c #D9EF9E",
"u. c #D6F293",
"i. c #DAF496",
"p. c #DFFF92",
"a. c #D7F19A",
"s. c #DAF39A",
"d. c #E0FF86",
"f. c #E2FF8C",
"g. c #E2FF94",
"h. c #EAFF93",
"j. c #E2FF9B",
"k. c #ECFF9C",
"l. c #F1FF9C",
"z. c #CEE0A2",
"x. c #D0E0A1",
"c. c #D6ECA3",
"v. c #D9EEA4",
"b. c #D8EDA8",
"n. c #DCF2A7",
"m. c #DEF2AB",
"M. c #DEF1B1",
"N. c #E3FDA4",
"B. c #ECFFA3",
"V. c #E4FAAC",
"C. c #EAFFAC",
"Z. c #F3FFA4",
"A. c #F4FFAC",
"S. c #F8FFAF",
"D. c #E4F7B7",
"F. c #E3F8B6",
"G. c #ECFFB3",
"H. c #E4F6B9",
"J. c #EDFEBA",
"K. c #F6FFB3",
"L. c #F8FFB5",
"P. c #F7FFBB",
"I. c #F8FFBB",
"U. c #EBFCC3",
"Y. c #EFFFC9",
"T. c #F5FFC3",
"R. c #F8FFC5",
"E. c #F4FFCC",
"W. c #F9FFC9",
"Q. c #FAFFD4",
"!. c #FBFFDD",
"~. c #FCFFE3",
"^. c #FDFFED",
"/. c #FEFFF3",
"(. c #FEFFFA",
/* pixels */
"                                                                                                                                                                                                            ",
"  (.(./.^././.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^././.(.(.  ",
"  (.^.!.W.W.W.W.E.R.W.W.W.W.R.R.W.R.R.R.W.R.W.R.W.W.W.R.W.R.R.R.W.R.W.R.W.R.W.R.W.R.R.T.W.R.W.R.W.R.W.R.W.R.W.R.R.W.W.R.W.R.W.R.W.R.W.R.W.R.W.R.W.W.W.R.W.R.W.R.W.R.W.R.W.R.W.R.W.R.R.T.W.R.W.W.W.Q.!.^.(.  ",
"  /.!.0 5 i i i e e r e i i e e i i i i e e k e i e i e i e e e i e i e k e i r i i i e i i i e i r i e i e i e i e i e k e i e i e i i i e i e i e i e i e i e i e i e i e k e i i i e i i i i 4 4 0 !./.  ",
"  ^.W.6 = % # % % # % % % % % % % % % % % # % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % # % % % % % % % % % % % % % # % % % % % % % % % % # % % % % % % % % % % % % % % % % % % % & 5 Q./.  ",
"  ^.W.r # @ X X O X X X X X X X X X + X O X X X X X X X X X X X X X + X X X X X X X X X X + + O X X X X O X X X X X + X X X X X X X O X + X X X X X X X X O X X + X X X X O X + X X X X X X X X X % r R./.  ",
"  ^.W.e % X X X X X X X X X X X X X X X X X X + X X X X + X X X X X X X X X X + X X X X X X X X X X X O X X X X X X X X X X X X + X X X X X X X X X X X X + X X X X X X X X X X X X X X X X X X X % i W.^.  ",
"  /.W.e % X O O X X X X X X X X X X X X X X X O X X X X X X X X X X X X X X X X X X + X X X X X X X X + + X X X X X X X X + X X X X X X X X X X X X X X X X X X X X + X X X X X + X X X X X X X X % i W.^.  ",
"  ^.W.i % @ X X X X X O O X X X X + X X + X X + X X X X X X X X + X X X X X X + X X X X X X X X X X + X X X X X X X X X X X X X X + X X X X X + X X X X X X X X X X X X X X X + X X X X + O X + . % r T.^.  ",
"  ^.W.4 % X X X X X X X X X X X X X O X X X X X X X X X X X X X X X X X X X X O X X X X X X X X X X X X X X X X + X X X X + X X X X X X X X X X X X X X X X X X X X X X X X X X X X O X X X X X o % e W.^.  ",
"  ^.W.4 % @ X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X + X X X X X X X + + X X X X X X X + X X X X X X X X O + O X X X X O X X X X X X O X X X X + X + X X X X X + X X X X X O % r W.^.  ",
"  ^.W.4 % O X X X X X X X X X X X X X X X X X X X X X + X X X X + X X X X X X X O X + X X X O X X X + O X X X X X X X X X X X + X X X X X X + X X X X X X X X X X X X X O X X X X X X X X X X X o % 4 R.~.  ",
"  ^.W.k % X X @ X X X X X X X X X X O X X X X X + X X X X X X @ X X X X X X X X + X X + O X X X X X X X X X X O + X X X X X X X X X X X X X X X O X X X X X X X X X X X X X X X X X X X X X X X @ % r W.^.  ",
"  ^.W.k % X @ @ X X X X X X X X X X + X O X X X X X X X X X X X X X X + + X + O X X X X + X X X O + X X X X X + X X X X X X X + X X X X X X X + X X X X X X X X X X X X X X X X X + X X X X X X @ % r R.^.  ",
"  ^.W.k # X X X X X X X X X X X X + X X + X X + X X X O X X X X X X X O X X X X X X X X X X X X X X X X X X X X O X X X X X X X X + + X X X X O + X X X X X X X X + X X O X X + X X O X X X X + X % e W.^.  ",
"  ^.W.i # X X X X X X X X X X X X X X X X X X X X X X + X X X X X X X X X X X X X X X X X X X X X X X + X X X X X + X X X + O X X O X X X X X X X X X X X X X X X X X X + X X X X X + X X + O X X % e W./.  ",
"  ^.W.e % o X X . . X X . X X X X X X X X X X X . + X X X X X X X O X X X X X O X @ X X X X X + X . X X X X O X X . . + X X X X X X X X + X X X X X X X O X X X O X X X X X X X X X X X X X X X X % e W.^.  ",
"  ^.W.e % o X X . X @ X X X X X X X X X @ O X X X X X X X X X X O X X X X X X @ X O X X X X X O X . + X . + X X . . + X X X X X X X X X + @ X X X X O X O O X X O X X X X X X X X X X X X X X X X % r R.^.  ",
"  ^.W.e % X X X X X X . X X X X X X X X @ O X X O @ . @ X @ X X @ @ X X X X X X @ X X X X X X + + @ X O + + X X + X X O X X X X X X X X @ @ + X X X X X X X X X X X X X X X X X X @ X X X X X X X % i W.^.  ",
"  ^.W.e % X X X . X O # # % # # X X X X @ O X X X . + o @ X @ X + @ X X X @ X X X X X X X O @ O # O # # # # O O O # O O O X X X X X X X @ @ O O # O O X X X X O O O O # # O X X X X X X X X X X X % i W.^.  ",
"  ^.W.i % X X X O O O $ i F y & O X X X X X X X + X + + O X X @ + + X X X X X X . @ X X + @ # $ * * * * * * & & & : % # O X @ X . @ X X + O % & > : # X X X X O # # $ $ ; % O X X X X X X X X X . % 5 W.^.  ",
"  ^.W.i % + + O O O * ` B.K.Z.Q $ # X X X X X O # # O + X @ X X + + X X X X X X X X X X + # b X.O.X.X.O.O.<.X.X.X.X.X.d # @ X X X . X X + # B X.4.l.% X X X O O # ~ [ X.h.$ # X X X X X X X X X X % i W.^.  ",
"  ^.W.k % X X X + % L L.5.F 9.S.M : # X X @ X # s y # X X X + + X O X O X X X X . X @ @ . $ ,.W.W.R.I.R.!.!.I.I.W.W.I.F % X X @ X X X + X # d.I.!.W.> O X X X O # &.I.R.L.4 O X X X X X X X X X X % k W.^.  ",
"  ^.W.4 % X X O # , K.e.= - i 5.l.p % X X X O $ k.8.% X X X + X @ + O + X X X X X X X X @ & w.!.E.*.8 z.^.^.*.7 :.Q.W.T $ X X X . X X O X % t E ^.Q.= X X X X O # 4 *.Q.L.4 ; X X X X X X X X X X # k W.^.  ",
"  ^.R.i % @ + # * ..Z.z $ # % y K.>.$ . X O # u W.P.& X . . X . X X X X X X X X X X X X X > x.W.! = e 2.^.~.J = e 9.W.) & X X X X + X X O # $ F ~.!.= X . X + O O & U W.I.i # O X X X X X X X X X % e W.^.  ",
"  ^.R.k % o X % i Z.5.= # X X * y.K.> O O X # m !.Q.> X . X X @ X X X X X X X X X . X . X $ V.I.= % & <.~.!.m % $ g I.q.$ X X X X X X X O O # n !.!.= X X + O @ X % S R.I.i % X X X X X X X X X X % e W.^.  ",
"  ^.W.k % @ + $ W I.` * # + + * _ I.M % # X O m Q.Q.> X @ X X X X X X . X X X @ X X X + . $ j.s.& # & <.~.!.n % # & C.,.% X X X X X X + + O # n !.!.= + X X X O X % T R.I.i % + X X X X X X X X X % k W.^.  ",
"  ^.W.k % + @ - m.W.v # @ + + % P I.0.> # X # , W.G.& X X X X X X X X X X X + @ X X X X X # g.) % # & <.~.!.n # O $ 9.O.% X X X X X X O X O # n !.!.& + X X X X X $ T R.I.i # . X X X X X X X X X % e W.^.  ",
"  ^.W.k % @ O w Q.Q.= O O . X % 5 L.S.i # X O % 0.o.% o + + X X X X X X X X X X X X X X . % 0.F % O & <.~.!.m # O % X.o.% . X X X X X X O @ # n !.!.= . X X X X @ $ K R.I.i # O X X X X X X X X X % r W.^.  ",
"  ^.W.k % O # n !.!.= X X o + # 4 L.R.K % . O O $ * O + X X X X X X X X X X X X @ O X X X % d.w % # * <.~.!.m % O # m [ % . X X X X X X + @ # n !.!.= X + X X X X $ K R.I.i % X X X X X X X X X + % r W.^.  ",
"  ^.W.i % O & <.~.!.= X . + O % i I.Q.q.& X X O O # O X X X X + X X X X X X X X O O X X . # &.w # # * <.~.~.m # O % g [ O X X X X + X X X O # F !.!.= X X X X X @ $ Y W.L.i % X X X O X X X X X X # r W.^.  ",
"  ^.W.i % # = s.~.!.& . + @ + % t P.!.D.& X X X O X . X X X X X X X X X X X X X X X X X X O &.= # # * <.~.!.m # O # > #.# X . . X X X X X O # n !.Q.= . X X X @ + % Y R.I.4 # X X X O X X X X X X % r W.^.  ",
"  ^.W.i % % t G.~.H.& X + o O # w N.~.Y.= X X X X X X X + X . X X X X X X X X X X @ X X + # &.> O # > O.~.!.m # O # & &.# . X X X X X X X X # n ~.!.> . X X X X X % Y R.I.e # O X X X X X X X X . % 4 W.^.  ",
"  ^.W.i # % k W.!.H.& X X X @ # w N.~.!.w o X X X X X + + X X X X X X X X X X X X X X X + # / : # O & <.~.!.m # O # : / # . X X X X X X X O # F !.!.= X O X X . @ $ K R.I.i % X X X X @ X X X X X % r R.^.  ",
"  ^.W.i % $ D E.~.F.& X X X + # w N.~.!.m # X X + X @ X X X X X X X X X X X X X X O @ + + O 3 # O # & <.~.!.m # O O # 3 O . X X X X O O X O # n !.!.> X O X X O X % Y R.P.e % + X X X X O X X X X % e W.^.  ",
"  ^.R.i % $ Y Q.~.F.& X X X O # w N.^.!.m % % # % # O + X @ O # % % ; # O X X X # % # # O O O O O O & <.~.!.m # O O O # O O # $ $ % # O X @ # H !.Q.> # % % # O X % K R.P.e % + X O # % $ % # X + % e R.^.  ",
"  ^.W.e % $ E Q.~.F.* o X X X # = n.~.~.! - = w e c # + + X O * F ,.n > # X X # =  .M = % # O X o # * <.~.!.n # O X O O # $ n 1.,.l & O O O # n ~.!.4 > o.L & # O % Y R.I.e % . X # : m <.l $ O . % e R.^.  ",
"  ^.W.e % * q.!.~.H.* O X X X # w n.~.~.<.= +.p.C.A.$ + . # * Q L.L.L.H % O # % $.A.Z.H ~ $ O X . # * <.~.!.n % O X X O & Q K.I.R.I.M # O @ # n ~.~.5 f.S.S.[ & # $ T R.L.e % X O % H L.I.A.u # O % e W.^.  ",
"  ^.R.e % * q.!.~.F.= O X X O # w N.^.~.<.w $.N.!.W.* o O % x S.[ e 2.Z.> O # 1 l.x l d.h.= # X . O * <.~.!.n # O O X % K L.X.e ;.R.k.> # O # F !.~.U f.y M A.x % $ Y R.L.i # O # : l.W Z k.%.= # % i W./.  ",
"  ^.W.r % * q.!.^.F.= + X X @ # w N.~.~.<.w w Y ^.!.- o O * a.C.= * 6 L.b % > { V = - Q Z.e # . . # * <.~.!.n # O X X $ v.R.w = P R.I.i % O # n ~.^.y.l $ > B.4.: $ Y R.I.i $ O $ [ g.4 4 @.S.x % % r W.^.  ",
"  ^.W.e % * q.~.~.F.= X X X X # w N.^.~.<.= & F !.!.= @ # , R.t.& $ Z P.@.w e 7.< # # * Z.t % + X # & O.~.!.n # O O X : P.!.t > 5 I.I.J $ o # F !.^.s.= # & F.J.& * Y R.P.i % % t k.@.= - M R.1.$ % r W.^.  ",
"  ^.W.e % * q.~.^.F.= . X X O # w N.~.~.<.* $ F ~.Q.= O % Q R.q.& $ _ R.p.e r k.% O o # 7.= # + X O & ,.~.!.n # O X X > Q.Q.b $ i I.R.Y $ @ # m !.~.,.* # * v.W.c = Y R.I.i % % A L...= $ b W.m.& # k R.^.  ",
"  ^.E.e % * q.!.^.F.& X X X X # w N.~.~.O.* % F !.!.= # - 5.R.W * * q.W.p.r 5 Z.- # O # | & O X X O $ O.~.!.n % @ X X > Q.!.b & i I.R.K $ o # n !.~.J % O * w.W.' t U R.I.i % * 1.R.O.& $ m Q.E.- % i W.^.  ",
"  ^.R.e % * q.!.~.H.& X X X + # w n.~.~.o.* % F !.!.= # w N.T.K $ $ 3.I.0.i 5 K...= * # h $ O X O # & ,.~.~.m # O X X $ C.I., * 4 I.R.T $ @ # n !.!.b # O & q.W.5.i U R.P.e % * v.W.<.w - F !.!.= $ k W.^.  ",
"  ^.W.e % $ Y Q.~.F.& X o @ @ # = N.~.!.m % % m !.!.= % e I.R.K % # v Z.V = k I.E.b.C = % O X . X # : ,.~.~.m # O X + # g N # % i I.R.Y $ O # m ~.!.= O X * q.E.j.5 *.R.I.i % * H.!.2.e e J ~.!.a * k W.^.  ",
"  ^.W.k % $ P Q.~.F.= + @ @ @ # w n.^.!.m # % m !.!.= % z I.R.Y % # * f # $ w C.~.^.Q.8.- # O X X O & O.~.!.m # X + + o # % % & 5 T.R.Y $ O # m !.!.= O . * q.Q.G.6 *.R.L.e % & T.~.F.,.O.a.!.W.b & 5 W.^.  ",
"  ^.R.e % $ C E.~.F.& X + + @ # = n.^.!.a # # n !.!.- $ J R.R.Y $ @ # # O # = i.~.(.^.!.<.= # X O O $ <.~.!.F # O X @ O o % = S :.!.W.Y $ O # n !.!.= @ O * q.E.I.7 *.R.P.e % = Q.^.W.I.K.L.T.K.j * k W.^.  ",
"  ^.W.e % # e T.!.F.& X . X @ # w N.~.Q.= O # n !.!.= % Y R.W.Y $ + + + @ # $  .!./.(.^.T.p % X O # & O.~.!.m # O X @ O $ p p.I.Q.!.W.K $ O % n !.!.= X X * q.Q.R.7 *.R.P.i % & !.^.x.7 r e e w % * k W.^.  ",
"  ^.W.r % # w C.!.F.& O X X . % i K.!.H.= O # n !.!.> # J R.W.Y % . . . O O O y T.^.(./.Q.W $ @ X O & <.~.!.m # O X X % x K.K.>.9 R.W.T $ O # n !.!.> X X * q.Q.R.7 *.R.P.e % - !.^.2.t * % % # O % k W.^.  ",
"  ^.W.r $ # = u.!.J.& X . X . % i I.Q.v.& O # n ~.!.> % J R.R.Y % + + + O o O * Y Y.!.~.!.q.* + X # & <.~.!.F # O O o = V.W.>.4 6 I.W.Y * O # m ~.Q.= X X * q.Q.I.7 *.R.L.e % = Q.~.<.* # + o o O % k R./.  ",
"  /.W.k % O $ o.~.!.= O X X . % i I.W.=.& O # n !.!.= $ J I.R.Y $ @ + X O O # % * p u.P.Q.n.* + + # & O.~.~.m # O O % a Q.Q.t - k I.R.K $ O # m !.!.= X X & q.Q.I.6 *.T.P.e % = Q.~.O.* O X o + + % r W.^.  ",
"  /.W.r % @ # c !.Q.= O X X X % k I.I.A % O # F !.!.= % z R.R.Y $ X @ @ ; % * ^ # # = z J.N.* . + O & <.~.!.m # O # $ ..!.Y.= % i I.R.Y % O # m ~.!.= X X * q.Q.N.6 I R.P.e % & U.!.<.* O X O @ O $ k W.^.  ",
"  /.W.4 % O O = W.Q.= O X X X $ C I.C.4 # O # m !.!.w % e L.R.K % X X O } * w &.# o # = _ j.$ + . # * <.~.!.m # O # = 8.!.F.= % i L.R.K $ O # m !.!.c # . * q.W.j.4 R T.P.e % & F.Q.O.& # o % 2 2 * r E./.  ",
"  ^.W.r % O + * b.R.v O O X + $ P I.5.= # O % m !.!.= # w j.R.Y $ @ @ # ^ t r h.% o o % F 0.% + O O * <.~.~.n # O # w j.Q.F.& % 5 I.W.K $ O # m !.~.n % o * w.W.O.e R R.L.i % & t.W.o.& # # $ ^ ; $ r W.^.  ",
"  ^.W.e % X + $ W P.M % @ o + % =.I.M % O O O m ~.!.= # - <.R.q.* O O # #.e r Z.: # O % n 6.# X X # * <.~.~.n # O # t j.!.F.= $ Y W.W.P % O # n !.~.<.* # & q.W.` w R R.I.i % $ =.T.O.* # # = | # % r R.^.  ",
"  ^.R.e % X X % e Z.@.* # @ O * s.G.& # O O # m !.!.= O % M W.w., O # 1 { w 5 A.N % @ % H ..% X X O * <.~.!.m # O # = N.~.Y.= = ;.W.W.R : # % m !.~.3.- # & F.R.p & Y R.I.i % % x L.g.= # # > &.# % e W.^.  ",
"  ^.W.i % X O # * ] k.w % O O & B.) * O @ O % n !.!.> O O , T.n.& # , } 1 & 5 S.5.= # % $.L % + X O : O.~.!.n # O O * u.~.~.z e v.W.Q.I Q $ % m !.~.e.y # & V.C.& & Y R.I.i % # = g.p.w % % b ..# % i W.^.  ",
"  ^.W.4 % X X O # : k.F & $ & ` h.t # X O # * J !.Q.i # O * a.P.p = k f.% % 4 S.Z.k > , l.y # O # % 4 q.~.!.K > % % *  .!.~.a.<.-.D.Q.c...& = K ~.~.=.X.= w K.<.& * R W.I.5 * # & V K.z = & 7.u # % k R.^.  ",
"  ^.W.4 % X X O O % c Z.J k K k.g % O X O % g.R.Q.Q.I.[ % % l A.y.R B...$ # = l.' j.U g.%.& # # v A.I.W.!.!.W.I.Z.= % p Q.^.Q.J.z i.!.Q.` = g.R.!.Q.6 k._ e.A.k = 0.R.Q.Q.I.] % % * N.V.U 8.&.* # % 5 R.^.  ",
"  ^.W.4 % X O X X # = o.R.W.R.C $ O @ @ + % ' ,.q.3.,.n # O * ! L.L.p.w # O * b 4 5.L.A.s # O # u o.q.q.q.w.q.2...& % * 2.W.T.Y = m R.I.t * ' 2.q.s.w L L.K.H = = Q ,.q.q.<.b # O % F K.L.j., % O # i W./.  ",
"  ^.W.i # X X X X O $ F Q.~.W.k % O X @ @ O % $ : $ $ # O O # % d j $ % @ O O # # % f , # O X O # % * * $ * : % % # O # & g y * # # g , # O # * * $ % % < < % # O % $ * * $ # O X O % : j : % O O % e R./.  ",
"  ^.W.k % X X X X X # m !.^.W.k % X O X O X X X X X X X O X X O o O o @ @ @ X O + X O O O O X X X X X @ @ + . X + + O o o o O @ X O O O O O X X O O . + O O O X O X O O O + o + X X O O O O . . @ % e W.^.  ",
"  ^.W.k % X X X X O O v !.^.W.4 % X X X X X X . X X X X + X + X @ O X X X X + + X X X X O X X X X X X X X X . X + . X X @ O o + X X O O O @ X X X X X X X X X X X X . O . O + + X + + @ o @ X X X % e W.^.  ",
"  ^.W.5 % X X X X O O = !.^.W.z % X X X X X . X X X X X X X O X + o X X @ X + + X X X X X X X X X X O X X . . X . @ X X X + + @ X X X X X X X X X + X X X X X X X X @ O X + + + X + + o @ O X X O % e W.^.  ",
"  ^.W.r $ X X X X X X & W.^.Q.K % X X @ X X X X X X X X X O X X X X X X X X X X X X X X X X O X X X + X X X X X X X X X X X X X X X X + X X X X X X X + X X X O + X X X X X X X X X X + X X X X X % i R.^.  ",
"  ^.W.4 % + X X X X X : D.~.Q.U $ X X X X X + X X O X X X X X X X X X X X + X X X X O + X X + X X X O X X X X X X + X X X X X + X X X X X X X X X X X O X X X X X X X X X X O + X X X X X X X X X % k W.^.  ",
"  /.R.i # X X X X X X * ;.Q.!.;.: X X @ X X X X X X X X X X X X X X X X X + X X X X X X X X + X X X X X O X X X X X X X X + X X X O + X X X X O X X X X X X + X X X X X X X X X X X X X X X X X . % r W.^.  ",
"  ^.W.i % + X X . X . % x R.Q.M.> # O X X X X X + X X X + + X X + O X X O X X X X X + X X X X X X + X X + X X + X O + X X O X X X X X X X X X + + X X X X X X X X + X X X @ X X . X O + X + O X X % r R.^.  ",
"  ^.W.i % X X X X X X # & 4.!.Q.l $ # X O O X X O X X X X X + + X X X X X X X X X X X + X X X X X X X X X X X X X X X X X X X X X X X X X + X X X X O X X X . X O + X X + X X X X X X X X + X X + % e W.^.  ",
"  ^.W.i % + O X X X X O # p G.Q.B.n $ O O X X X X X X X X X + + X X X + + X X X X X X X X X X X X X X X X X X X X X X X X X X X O X + X X X X X X X + X O X X X X X X X X O X X X X + X X X X X + % e W.^.  ",
"  ^.W.4 % O X X X X X O O % p g.I.I.l.& # O X X X X X X X X X X X X O X X X + X X X X X X X X + X X X + + X X X X X O X X X + X + X X X X X X X X X X + + X X X X X X X X X X X X O X X X + X X X % 5 W.^.  ",
"  ^.W.4 % @ X X . X X X O O % = ) ,.X.> # X X X X X X X X + X X X X + X X X O X X X O + X X X O X X X X O X X X X + X X + X O X X X X X X X + O X X X X X X X + X X X X + X X X X + X X X O X X X % i W.^.  ",
"  ^.W.5 % X X X . X X X X O O # % $ % # X X @ X X @ X X X X + + X X X X O + X X X X + X X X X X X X X X O + X X X X X X X + X X X X X X X X X X X X X X X X X O X X X X X X X X X X X O + X X X X % k W.^.  ",
"  ^.R.e % O X X . . X X X X O + X X X O X X X X + X X X @ X + + X X X X X X X X X X X X X X X X X @ X X X X X X X X X X X X X X X X X X X X X X X @ X X X X X X X X X + X X X X X X X X X X X X X % e W.^.  ",
"  ^.R.i % X . + X X X X + X + + X X @ O X X X X X X X X X X . X X X X X X + X X X X X X X X + X X X X X + X X X + X X X X X X X X O X X X X X X X X X X @ X X X X X X X X X X X X X X + X X X X . % 4 W.^.  ",
"  ^.W.i % X X . X X + X O + + + X X @ X X X O X X X X X X X X X X X + X X X X X X X + O X X X X X + O . X X X X X X O + X X X + X X + X X X + X X + O X X X X X X X X O + X X + X X X X + X X X X % e W.^.  ",
"  ^.W.e % X . + X X X X + + + + X @ @ + X X X X X X X X X O @ + + X X X X + X X X + X X X O X . X X O + X X X X X X X X X X X O + X X X X X X O X X O + X X X X X + X X X X X X X X X X O + X X O % e W.^.  ",
"  ^.Q.5 & % % % # # % % % % % % % % % # % # # % # % % % # % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % = 5 W./.  ",
"  /.!.0 5 e e e 4 i i k i i i i i i i i i i i i 4 4 i i i e i k r e k e k e i e r e k e e e r e e e k e i e i e i e e e i e k e e e i e e e k e e e r e i e k e r e i e k e r e k e k e k e i i r 5 0 !./.  ",
"  (.^.!.Q.R.W.W.W.W.W.W.R.W.W.W.R.R.W.R.W.W.W.W.W.W.W.W.W.R.W.W.W.W.W.R.W.W.W.W.W.W.R.W.W.W.W.W.W.W.W.R.W.W.W.W.W.W.W.W.W.W.R.W.W.W.W.W.W.W.R.W.W.W.W.R.W.R.W.W.W.W.W.W.W.W.W.R.W.W.R.W.W.W.W.R.W.W.!.^.(.  ",
"  (.(./.^.^.^.^.^.^.^./.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.^.^.^.^.^.^.^.^.^.^.^.^./.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./././.(.  ",
"                                                                                                                                                                                                            "
};


